<?php
// enum HttpStatusCode: int {
//     OK = 200;
//     CREATED = 201;
//     NO_CONTENT = 204;
//     BAD_REQUEST = 400;
//     UNAUTHORIZED = 401;
//     FORBIDDEN = 403;
//     NOT_FOUND = 404;
//     INTERNAL_SERVER_ERROR = 500;
// }

define('HTTP_STATUS_CODE_OK', 200);
define('HTTP_STATUS_CODE_CREATED', 201);
define('HTTP_STATUS_CODE_NO_CONTENT', 204);
define('HTTP_STATUS_CODE_BAD_REQUEST', 400);
define('HTTP_STATUS_CODE_UNAUTHORIZED', 401);
define('HTTP_STATUS_CODE_FORBIDDEN', 403);
define('HTTP_STATUS_CODE_NOT_FOUND', 404);
define('HTTP_STATUS_CODE_CONFLICT', 409);
define('HTTP_STATUS_CODE_INTERNAL_SERVER_ERROR', 500);
?>